[package]
name = "cidrrr"
version = "2025.7.24"
edition = "2024"
authors = ["Stefan Ruzitschka <stefan@icepuma.dev>"]
description = "Convert a CIDR block to a list of IPs"
keywords = ["ip", "cidr", "ipv4", "ipv6"]
repository = "https://github.com/icepuma/cidrrr"
readme = "README.md"
license-file = "LICENSE"

[dependencies]
clap = { version = "4.5.47", features = ["cargo", "derive"] }
ipnet = "2.11.0"
serde = { version = "1.0.219", features = ["derive"] }

[dev-dependencies]
pretty_assertions = "1.4.1"

[profile.release]
lto = true
strip = true
opt-level = "z"
codegen-units = 1
