name: Test
on:
  push:
    branches:
      - "main"
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
          - windows-2022
          - windows-2025
          - macos-13
          - macos-14
          - macos-15
    env:
      CARGO_TERM_COLOR: always
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@nextest
      - run: cargo fmt -- --check && cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo nextest run
